name: Auto Create PR

on:
  push:
    branches:
      - dev1
      - feat1

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Auto PR from ${{ github.ref_name }}"
          body: "Automated PR creation"
          reviewers: poornimadyamanna   # 👈 your GitHub username

      - name: Enable Auto Merge
        run: gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
